xcodeproj 'HJDemo.xcodeproj'

#source 'https://github.com/jixuhui/HJSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios,'7.0'
#pod 'HJArchitecture'
pod 'Masonry'
pod 'AFNetworking', '2.6.3'
pod 'MJRefresh'
pod 'RDVTabBarController', '1.1.9'
pod 'SDWebImage', '3.7.3'
pod 'MPMessagePack'
pod 'UITableView+FDTemplateLayoutCell'
pod 'JSONKit', '~> 1.5pre'